config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts, :only => [:new, :create, :index]
  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @post = Post.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def new
    @post = Post.new
    @user = current_user
  end

  private

  def post_params
    params.require(:post).permit(:body, :title, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
  <nav class="navbar navbar-light navbar-expand-lg bg-dark rounded-bottom">
    <div class="container-fluid">
      <%= link_to "Members Only", root_path, class: 'navbar-brand fs-2 text-danger' %>
      <% if user_signed_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Create Post", new_post_url, class: "nav-link fs-5 text-light" %>
        </ul>
      <% end %>
        <div class="d-flex flex-column justify-content-between">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <% if !user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, class: "nav-link fs-5 text-light"%>
              </li>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_url, class: "nav-link fs-5 text-light"%>
              </li>
            </ul>
            <% else %>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to "Log out", destroy_user_session_path, :method=>'delete', class: "nav-link fs-5 text-light" %>
            </ul>
            <% end %>
          </div>
        </div>
    </div>
  </nav>
  <div class="container mt-3">
    <% if !notice.nil? %>
    <div class="alert alert-danger" role="alert">
      <%= notice %>
    </div>
    <% end %>

    <% if !alert.nil? %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/index.html.erb
<% @post.each do |post| %>
  <div class="card my-2">
    <div class="card-body">
      <div class="d-flex justify-content-between flex-row">
        <h3 class="text-danger"><%= post.title %></h3>
        <% if user_signed_in? %>
          <p><strong class="text-danger">Author:</strong> <%= post.user.email %></p>
        <% end %>
      </div>
      <p><%= post.body %></p>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Create Post</h1>

<%= form_with class: 'd-flex flex-column w-100',model: @post do |post| %>
  <%= post.label :title, class: 'form-label'%>
  <%= post.text_field :title, class: 'form-control' %>
  <%= post.label :body, class: 'form-label' %>
  <%= post.text_area :body, class: 'form-control' %>
  <br>
  <%= post.submit 'Save Post', class: 'btn btn-danger'%>
<% end %>